workflow:
  generator:
    workflows:
      release-train:
        build:
          runs-on: ubuntu-latest
        test:
          runs-on: ubuntu-latest
    project:
      java:
        versions:
          primary: 17
